### ISSUE TITLE
2015/05/corewallet has no hdkeystore.h

### ISSUE THREAD

**Issue by faizkhan00** [jonasschnelli/bitcoin#4]
I believe the file is missing, it should be in src/, should it not? The reference is in corewallet/corewallet_db.h:

```
#include "corewallet/corewallet_basics.h"
#include "corewallet/logdb.h"
#include "key.h"
#include "hdkeystore.h"
```

it also causes a build error, naturally:
```
./corewallet/corewallet_db.h:12:24: fatal error: hdkeystore.h: No such file or directory
 #include "hdkeystore.h"
                        ^
compilation terminated.
Makefile:3579: recipe for target 'corewallet/libbitcoin_corewallet_a-corewallet.o' failed
```

**Comment by jonasschnelli** [comment]
Thanks for reviewing testing. It's under hard development, so don't expect that it compiles straight off (nevertheless I try to build stable commits).

Your right. `#include "hdkeystore.h"` must be `#include "corewallet/hdkeystore.h"`. Will fix.

**Comment by faizkhan00** [comment]
Sorry @jonasschnelli I should have been more specific, I mean `hdkeystore.h` doesn't exist (and is not checked in) to the actual repository:

https://github.com/jonasschnelli/bitcoin/tree/2015/05/corewallet/src/corewallet/hdkeystore.h
https://github.com/jonasschnelli/bitcoin/tree/2015/05/corewallet/src/hdkeystore.h

Both return `404` for me- but yes, testing this and hoping to help review the core-wallet !

**Comment by jonasschnelli** [comment]
@faizkhan00: right. I missed those file during `git add`. Added them and force pushed some secs ago.

**Comment by jonasschnelli** [comment]
But they are not in `/src` but rather in `/src/corewallet/`

**Comment by jonasschnelli** [comment]
Pushed a new version which is stable in case of hd wallet.
Mind the initial hd steps:

* `./src/bitcoin-cli --regtest corewallet/addwallet walletid=test` (adds a fresh wallet)
* `./src/bitcoin-cli --regtest corewallet/hdaddchain` (initialized a new bip32 chain of keys)
* `./src/bitcoin-cli --regtest corewallet/hdgetaddress` (should give your a new bip32 derived address)
* `./src/bitcoin-cli --regtest corewallet/hdgetaddress index=0` (should give your the same address again)

**Comment by faizkhan00** [comment]
awesome. will test this today and let you know how it goes, thanks @jonasschnelli !
